spring.application.name=task

# Enable H2 Console
spring.h2.console.enabled=true
# JDBC URL for in-memory DB
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate/JPA settings
spring.jpa.hibernate.ddl-auto=update

